Control the access_limiter per file and by the specified time slots
matsumoto-r/http-access-limitter pull request #2
Opened 2016-10-05 05:49 UTC by takumakume

# Control the access_limiter per file and by the specified time slots

### 概要

#### access_limiterに以下の機能を追加した。

- ファイル単位で同時接続数を制限できるようにした。(Add class MaxClientsHandler)
  - 制限を有効にする時間帯を複数指定することができる。
  - localmemcacheに設定を格納して都度参照するため、設定変更に伴う設定のリロードは不要。

- ファイル単位で同時接続数を制限の設定はファイルベースのlocalmemcacheに以下のような設定を行う。
  - key
  
    ```
    /path/to/example.php
    ```
    
  - value (JSON形式の文字列)
  
    ```json
    {
      "max_clients" : 30,
      "time_slots" : [
        { "begin" : 1100, "end" : 1200 },
        { "begin" : 2200, "end" : 2300 }
      ]
    }
    ```
    
  - `/path/to/example.php` への `11:00-12:00` or `22:00-23:00` の間のアクセスは、同時に `30` までしかアクセスできない設定。

#### Unitテストを実装した。

- 以下のようにすることで、access_limiterのユニットテストを実行できる。

  ```shell
  rake
  ```

  - 実行結果として以下の出力が得られる。

    ```
    # Running tests:
    ...
    Finished tests in 0.003936s, 762.1951 tests/s, 3556.9106 assertions/s.
    3 tests, 14 assertions, 0 failures, 0 errors, 0 skips
    ```

#### E2Eテストを実装した。

- E2Eテストは以下の目的で行う。
  - access_limiterを実装した前後でパフォーマンス劣化がどの程度発生するかを確認するため。
  - MaxClientsHandlerの追加など、機能を追加した場合に想定される運用パターンでパフォーマンス劣化がどの程度発生するか確認するため。
  - プロセスが使用するメモリを負荷テスト前後で取得し、メモリリークが発生していないかを確認するため。
  - 性質上 lock/unlock をしながら同時接続数のカウントを行うため、Race conditionが発生していないかを確認するため。
  - 同時アクセス数が制限に達した場合にステータスコードを変えてレスポンスを返しているか確認するため。

- 以下のようにすることで、E2Eテストを実行できる。

  ```shell
  rake e2e:test
  ```

  - 実行結果として以下の出力が得られる。
    - https://gist.github.com/takumakume/740da02b34b6157a9e31822f9a840e5e

### 以下のmgemが要件に追加されます

- [mattn/mruby-json](https://github.com/mattn/mruby-json)
- TestOnly: [iij/mruby-mtest](https://github.com/iij/mruby-mtest)

### パフォーマンス比較結果

###### 環境
  - MacBook Pro (Retina 13-inch、Early 2015)
  - CPU: 3.1 GHz Intel Core i7
  - RAM: 16 GB

###### リクエスト
  - [matsumoto-r/ab-mruby](https://github.com/matsumoto-r/ab-mruby)で実施。
  - 設定 (10万リクエスト100多重)
    ```ruby
    add_config(
      "TotalRequests"         => 100000,                    # int
      "Concurrency"           => 100,                       # int max 20000
      "KeepAlive"             => true,                      # true or false or nil
      "VerboseLevel"          => 1,                         # int 1 ~ 5
      "SilentMode"            => true,
    )
    ```

###### 以下の5パターンでパフォーマンスの計測を行った。

  - httpd(pure)
  - httpd + access_limiter
  - httpd + access_limiter + max_clients_handler
    - 制限設定がないファイルに対するアクセス
    - 制限設定が存在するファイルに対するアクセス
    - 制限設定が存在し、有効にする時間を指定しているファイルに対するアクセス

#### Request/sec

| テストパターン | Request/sec | httpd(pure)を基準とした劣化率
| -----------  | ----------- | ----
| httpd(pure)                                                     | 1108 |  0.0%
| httpd + access_limiter                                          | 998  |  9.9%
| httpd + access_limiter + max_clients_handler (制限設定無)         | 978  | 11.7%
| httpd + access_limiter + max_clients_handler (制限設定有)         | 914  | 17.5%
| httpd + access_limiter + max_clients_handler (制限設定有+時間指定) | 898  | 18.9%

- 多少の劣化はみられるが、運用上大きな問題にはならないと考えられる。

#### メモリ使用量

パフォーマンス計測前後のhttpdのメモリ使用量を `ps aux` で取得した結果を比較している。

| テストパターン | VmSizeの増加率 | VmRssの増加率
| -----------  | ----------- | ----
| httpd(pure)                                                     | 94.8 | 95.5%
| httpd + access_limiter                                          | 94.8 | 95.6%
| httpd + access_limiter + max_clients_handler (制限設定無)         | 94.8 | 95.6%
| httpd + access_limiter + max_clients_handler (制限設定有)         | 94.8 | 95.6%
| httpd + access_limiter + max_clients_handler (制限設定有+時間指定) | 94.8 | 95.7%

- 通常のhttpdともほぼ変化もなく、メモリリークは発生していない。

#### レースコンディション

- 発生していない。

#### 制限値に達した場合のステータスコードの切り替え

- いずれのパターンも問題なく切り替えることができた。

2016-10-05 06:34 UTC, tap1ra commented on access_limiter/access_limiter_init.rb
> +  def limit?
役割と引数・戻り値の型のコメントがあったらいいと思いました(パッと見でわかるやつは不要ですが)

2016-10-05 06:36 UTC, dojineko commented on access_limiter/access_limiter_init.rb
> +    false
こことか、ifの条件の結果そのものを返して良いように見えます 😄 

```diff
- return true if config && max_clients > 1 && max_clients < @access_limiter.current && time_slots?(config["time_slots"])
- false
+ config && max_clients > 1 && max_clients < @access_limiter.current && time_slots?(config["time_slots"])
```

2016-10-05 06:49 UTC, matsumotory requested changes
設計面は良いと思います。すごく良くなりました。後は、細かい指摘をしましたのでご確認お願いします。

2016-10-05 06:49 UTC, matsumoto-r commented on access_limiter/access_limiter.rb
> -  limit = AccessLimiter.new r, cache, config
このメインのスクリプト（もはや設定）で、cacheの種類やリクエストの情報を渡すことによって、インタフェースをなるべくいじることなく今後の変更を行えるようにしておきたいので、元の引数の方が今後の保守面や、利用者がインタフェースの変更を意識することなく使えて便利だと思います。

2016-10-05 06:49 UTC, matsumoto-r commented on access_limiter/access_limiter.rb
> +      Server.errlogger Server::LOG_NOTICE, "access_limiter: increment: file:#{file} counter:#{current}"
これ僕の元コードでもあるんですが、この辺のメッセージのプライオリティはINFOレベルで良さそうですね。

2016-10-05 06:49 UTC, matsumoto-r commented on access_limiter/access_limiter_init.rb
> +  def initialize(access_limiter, filename)
filenameはデータストアファイルパスのはずなので、それがわかりやすい変数名が良いと思います。

2016-10-05 06:49 UTC, matsumoto-r commented on access_limiter/access_limiter_init.rb
> +    time_slots.find do |t|
複数のタイムレンジを設定できているようになっていて良いですね。

2016-10-05 06:49 UTC, matsumoto-r commented on access_limiter/access_limiter_init.rb
> +    return true if config && max_clients > 1 && max_clients < @access_limiter.current && time_slots?(config["time_slots"])
`config && max_clients > 1 && max_clients < @access_limiter.current` このあたりは `max_clients?`みたいな感じでメソッドに分けると、条件がきれいになった上に意味がわかりやすくなって可読性が上がるように思います。

2016-10-05 07:34 UTC, matsumoto-r commented
localmemcacheのファイルパス指定で作るデータ領域は、メモリマップドなファイルであるため、サーバ再起動などをすると失われそうです。それが不都合な場合は、何か永続化するためのdump restore機能だったりがいりそうです。

また、incrementしてdecrementするまにApacheがsegfaultで落ちた場合に、カウンタの齟齬が起きる可能性もあるので、その検知と対応も必要そうです。

2016-10-07 16:26 UTC, takumakume commented
@matsumoto-r 

> localmemcacheのファイルパス指定で作るデータ領域は、メモリマップドなファイルであるため、サーバ再起動などをすると失われそうです。それが不都合な場合は、何か永続化するためのdump restore機能だったりがいりそうです。

再起動の検証を実施したところ、ファイルベースで生成したlocalmemcachは消滅せず正常に読み出すことができましたので特に処理を追加していません。

> また、incrementしてdecrementするまにApacheがsegfaultで落ちた場合に、カウンタの齟齬が起きる可能性もあるので、その検知と対応も必要そうです。

当初のコードにあったように、Worker Init時にキャッシュのclearをすることを検討しましたが動作環境によっては頻繁にWorkerプロセスの生え変わりが発生する可能性があり、access_limiter本来の機能が損なわれると考え適応しませんでした。
根本的なカウンター不整合に対応するためには、大幅な改修と仕様変更が伴うため、現時点での運用は以下を行うようにすればある程度は緩和すると考えました。

- 1時間に1回程度、Apacheのエラーログからsegfaultされていないか確認し、segfaultしていた場合にキャッシュをクリア (環境によって実行スパンを検討)
- 1日1回程度、念のためにキャッシュをクリア

----

ご指摘いただいたコードについては、修正しましたのでご確認お願い致します。

2016-10-14 02:37 UTC, takumakume commented
Workerプロセスが予期せぬ終了をした時に、access_limiterの同時接続カウンターが上がりっぱなしになってしまう可能性があった。
その為、カウンターの形式を以下のようにすることで対応した。

- 従来

  ```
  2
  ```

- 変更後

  ```
  [ 1476116100, 1476116120 ]
  ```

  - カウンターをインクリメントする処理は、アクセスがあった時間のUnixtimeを配列にPushする。
  - 既存のインターフェイスはそのままでカウントの処理のみ変更した。
  - 現在のカウンターは配列のサイズとなる。
  - 現在のカウンターを参照する前に `AccessLimiter#keep_inconsistency` を実行することで、古いカウンターを削除することができる。
  - AccessLimiterを利用するときに以下のようにすることで、カウンターを削除する対象の時間を変更できる。デフォルトは600秒。

    ```ruby
    # :expire_time で指定することができる。
    config = {
      :target      => request.filename,
      :expire_time => 1200
    }
    limit = AccessLimiter.new request, cache, config
    ```

### パフォーマンス比較結果

###### 環境
  - MacBook Pro (Retina 13-inch、Early 2015)
  - CPU: 3.1 GHz Intel Core i7
  - RAM: 16 GB

###### リクエスト
  - [matsumoto-r/ab-mruby](https://github.com/matsumoto-r/ab-mruby)で実施。
  - 設定 (10万リクエスト100多重)
  
    ```ruby
    add_config(
      "TotalRequests"         => 100000,                    # int
      "Concurrency"           => 100,                       # int max 20000
      "KeepAlive"             => true,                      # true or false or nil
      "VerboseLevel"          => 1,                         # int 1 ~ 5
      "SilentMode"            => true,
    )
    ```

###### 以下の5パターンでパフォーマンスの計測を行った。

  - httpd(pure)
  - httpd + access_limiter
  - httpd + access_limiter + max_clients_handler
    - 制限設定がないファイルに対するアクセス
    - 制限設定が存在するファイルに対するアクセス
    - 制限設定が存在し、有効にする時間を指定しているファイルに対するアクセス

#### Request/sec

| テストパターン | Request/sec | httpd(pure)を基準とした劣化率
| -----------  | ----------- | ----
| httpd(pure)                                                     | 1165 |  0.0%
| httpd + access_limiter                                          | 894  | 23.2%
| httpd + access_limiter + max_clients_handler (制限設定無)         | 927  | 20.4%
| httpd + access_limiter + max_clients_handler (制限設定有)         | 738  | 36.6%
| httpd + access_limiter + max_clients_handler (制限設定有+時間指定) | 711  | 38.9%

- インクリメント時間を考慮したカウンターに変更したことにより、従来よりパフォーマンス劣化が倍になった。
- `access_limiter + max_clients_handler (制限設定無)` が素のaccess_limiterより高速なのはカウンターを参照する前に制限設定がなかったら処理をしないためである。
- `max_clients_handler` で制限した場合に30％を超えるパフォーマンス劣化が見られるが、制限対象であるため大きな問題にはならないと考える。

参考: [E2Eテスト結果](https://gist.github.com/takumakume/2c0bd4b71f9f38cd7360f6e39a68ecd9)

2016-10-14 06:25 UTC, matsumoto-r commented
このベンチマークのリクエスト先のコンテンツはなんですか？

2016-10-17 00:00 UTC, takumakume commented
phpinfo()です。

2016-10-22 17:54 UTC, takumakume commented
## Worker Processのセグフォを考慮したカウンターの仕様変更

- 以下の2つのカウンターで構成される

  - 同時接続数をカウントするデータ
  
    ```
    # key
    key
    # value
    2
    ```

  - カウンタが1になったときの時間を記録するデータ

    ```
    # key
    create_time_key
    # value
    1451611800
    ```

カウンターの `increment` を行う前に `create_time_key` に設定されている時間から一定時間経過していないか確認し、経過していればカウンタを `0` にする。

----

## 最終的なパフォーマンステストを実施した

### 環境

```
CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz 24コア
RAM: 32GB
```

```
ツール: matsumoto-r/ab-mruby
リクエスト数: 10万
並列リクエスト数: 100
経路: localhost->
```

##### `phpinfo()`へのアクセス(軽量コンテンツ)

| テストパターン | Request/sec | httpd(pure)を基準とした劣化率
| -----------  | ----------- | ----
| httpd                                                                       | 4259 |  0.0%
| httpd + mod_mruby + access_limiter + max_clients_handler (制限設定無)         | 4144  | 2.7%
| httpd + mod_mruby + access_limiter + max_clients_handler (制限設定有)         | 2948  | 30.7%
| httpd + mod_mruby + access_limiter + max_clients_handler (制限設定有+時間指定) | 2851  | 33.0%

##### `Wordpress`へのアクセス

| テストパターン | Request/sec | httpd(pure)を基準とした劣化率
| -----------  | ----------- | ----
| httpd                                                                       | 59 |  0.0%
| httpd + mod_mruby + access_limiter + max_clients_handler (制限設定無)         | 57  | 3.3%
| httpd + mod_mruby + access_limiter + max_clients_handler (制限設定有)         | 56  | 5.08%
| httpd + mod_mruby + access_limiter + max_clients_handler (制限設定有+時間指定) | 56  | 5.08%

- カウンタ仕様を現在のものに変更することで、パフォーマンスの向上が見られた。
- 制限対象でないアクセスへのパフォーマンス劣化は `2.7%` と低いパフォーマンス劣化である。
- Wordpressなど、DB接続などのオーバヘッドが大きいコンテンツへのアクセスの場合はパフォーマンス劣化の違いはほぼなかった。
- 軽量コンテンツに対するパフォーマンステストによると、制限対象に入れることでmutexのロック/アンロックやカウンタの処理により30%程度のパフォーマンス劣化が発生した。
  - その為、アクセス全体を制限対象に入れるような使い方をすると、環境によっては大幅なパフォーマンス劣化につながる可能性がある。

----

## 設定ツール

- access_limiter + max_clients_hander を利用するために、制限情報を `localmemcache` に設定する必要がある。
- 以下のリポジトリに設定ツールを作成した

https://github.com/takumakume/max_clients_handler_cli

2016-10-28 02:17 UTC, takumakume commented
動作問題なさそうなのでマージお願いします。
設定ツールは別途PR出します。

2016-10-28 02:19 UTC, merged

2016-10-28 02:19 UTC, matsumoto-r commented
Thanks!

2016-10-28 02:21 UTC, matsumoto-r commented
@takumakume I add you to collaborators. Thanks!